### PR TITLE
Add job classes data

### PR DESCRIPTION
**Pull request by nomes**
Still missing some data, but structure should remain the same.

### CODE REVIEW

**Comment by alexchao** [comment]
Cool. Is this a file we want accessible on the website? If not, maybe we should put it in a separate "resources" folder or something at the top level.

**Comment by nomes** [comment]
Yea I'll do that. Didn't know where else to put it.

**Comment by nomes** [comment]
So this is the full job spec file. I think it should be good to go unless you see otherwise.

**Comment by alexchao** [comment]
@nomes nice work =)

this data is for sure going to change, so we'll need to think about the right way to make those changes and have them reflected on the site.

**Pull request merged**
